package dux.org.hibernate.boot.internal;

import org.hibernate.boot.internal.SessionFactoryBuilderImpl;
import org.hibernate.boot.spi.MetadataImplementor;
import org.junit.Before;
import org.junit.Test;

import com.github.docteurdux.test.AbstractTest;

import dum.org.hibernate.boot.spi.DummyMetadataImplementor;
import dus.hibernate.core.HibernateCoreSummaryTest;

public class SessionFactoryBuilderImplTest extends AbstractTest {
	@Before
	public void before() {
		requireSources(HibernateCoreSummaryTest.MVNNAME, SessionFactoryBuilderImpl.class);
	}

	@Test
	public void test() {

		DummyMetadataImplementor metadata = new DummyMetadataImplementor();
		SessionFactoryBuilderImpl sfbi = new SessionFactoryBuilderImpl(metadata);

		/*-
		addEntityNameResolver(EntityNameResolver...)
		addSessionFactoryObservers(SessionFactoryObserver...)
		allowOutOfTransactionUpdateOperations(boolean)
		applyAutoClosing(boolean)
		applyAutoFlushing(boolean)
		applyAutomaticEvictionOfCollectionCaches(boolean)
		applyBatchFetchStyle(BatchFetchStyle)
		applyBeanManager(Object)
		applyCacheRegionPrefix(String)
		applyConnectionHandlingMode(PhysicalConnectionHandlingMode)
		applyConnectionProviderDisablesAutoCommit(boolean)
		applyConnectionReleaseMode(ConnectionReleaseMode)
		applyCurrentTenantIdentifierResolver(CurrentTenantIdentifierResolver)
		applyCustomEntityDirtinessStrategy(CustomEntityDirtinessStrategy)
		applyDefaultBatchFetchSize(int)
		applyDefaultEntityMode(EntityMode)
		applyDefaultNullPrecedence(NullPrecedence)
		applyDirectReferenceCaching(boolean)
		applyEntityNotFoundDelegate(EntityNotFoundDelegate)
		applyEntityTuplizer(EntityMode, Class<? extends EntityTuplizer>)
		applyEntityTuplizerFactory(EntityTuplizerFactory)
		applyGetGeneratedKeysSupport(boolean)
		applyIdentifierRollbackSupport(boolean)
		applyInterceptor(Interceptor)
		applyJdbcBatchingForVersionedEntities(boolean)
		applyJdbcBatchSize(int)
		applyJdbcFetchSize(int)
		applyJtaTrackingByThread(boolean)
		applyLazyInitializationOutsideTransaction(boolean)
		applyMaximumFetchDepth(int)
		applyMinimalPutsForCaching(boolean)
		applyMultiTableBulkIdStrategy(MultiTableBulkIdStrategy)
		applyMultiTenancyStrategy(MultiTenancyStrategy)
		applyName(String)
		applyNameAsJndiName(boolean)
		applyNamedQueryCheckingOnStartup(boolean)
		applyNullabilityChecking(boolean)
		applyOrderingOfInserts(boolean)
		applyOrderingOfUpdates(boolean)
		applyPreferUserTransactions(boolean)
		applyQueryCacheFactory(QueryCacheFactory)
		applyQueryCacheSupport(boolean)
		applyQuerySubstitutions(Map)
		applyResultSetsWrapping(boolean)
		applyScrollableResultsSupport(boolean)
		applySecondLevelCacheSupport(boolean)
		applySqlComments(boolean)
		applySqlFunction(String, SQLFunction)
		applyStatelessInterceptor(Class<? extends Interceptor>)
		applyStatementInspector(StatementInspector)
		applyStatisticsSupport(boolean)
		applyStrictJpaQueryLanguageCompliance(boolean)
		applyStructuredCacheEntries(boolean)
		applyTempTableDdlTransactionHandling(TempTableDdlTransactionHandling)
		applyValidatorFactory(Object)
		build()
		buildSessionFactoryOptions()
		connectionProviderDisablesAutoCommit()
		disableJtaTransactionAccess()
		disableRefreshDetachedEntity()
		enableReleaseResourcesOnCloseEnabled(boolean)
		getBaselineSessionEventsListenerBuilder()
		getBatchFetchStyle()
		getBeanManagerReference()
		getCacheRegionPrefix()
		getConnectionReleaseMode()
		getCriteriaLiteralHandlingMode()
		getCurrentTenantIdentifierResolver()
		getCustomEntityDirtinessStrategy()
		getCustomSqlFunctionMap()
		getDefaultBatchFetchSize()
		getDefaultEntityMode()
		getDefaultNullPrecedence()
		getEntityNameResolvers()
		getEntityNotFoundDelegate()
		getEntityTuplizerFactory()
		getInterceptor()
		getJdbcBatchSize()
		getJdbcFetchSize()
		getJdbcTimeZone()
		getMaximumFetchDepth()
		getMultiTableBulkIdStrategy()
		getMultiTenancyStrategy()
		getPhysicalConnectionHandlingMode()
		getQueryCacheFactory()
		getQuerySubstitutions()
		getSchemaAutoTooling()
		getServiceRegistry()
		getSessionFactoryName()
		getSessionFactoryObservers()
		getStatelessInterceptorImplementor()
		getStatementInspector()
		getTempTableDdlTransactionHandling()
		getValidatorFactoryReference()
		isAllowOutOfTransactionUpdateOperations()
		isAllowRefreshDetachedEntity()
		isAutoCloseSessionEnabled()
		isAutoEvictCollectionCache()
		isCheckNullability()
		isCollectionJoinSubqueryRewriteEnabled()
		isCommentsEnabled()
		isConventionalJavaConstants()
		isDirectReferenceCacheEntriesEnabled()
		isFlushBeforeCompletionEnabled()
		isGetGeneratedKeysEnabled()
		isIdentifierRollbackEnabled()
		isInitializeLazyStateOutsideTransactionsEnabled()
		isJdbcBatchVersionedData()
		isJpaBootstrap()
		isJtaTrackByThread()
		isJtaTransactionAccessEnabled()
		isMinimalPutsEnabled()
		isNamedQueryStartupCheckingEnabled()
		isOrderInsertsEnabled()
		isOrderUpdatesEnabled()
		isPreferUserTransaction()
		isProcedureParameterNullPassingEnabled()
		isQueryCacheEnabled()
		isQueryParametersValidationEnabled()
		isReleaseResourcesOnCloseEnabled()
		isScrollableResultSetsEnabled()
		isSecondLevelCacheEnabled()
		isSessionFactoryNameAlsoJndiName()
		isStatisticsEnabled()
		isStrictJpaQueryLanguageCompliance()
		isStructuredCacheEntriesEnabled()
		isWrapResultSetsEnabled()
		markAsJpaBootstrap()
		unwrap(Class<T>)
		*/
	}
}
