package dum.org.hibernate.engine.jdbc.spi;

import java.sql.PreparedStatement;
import java.sql.Statement;

import org.hibernate.ScrollMode;
import org.hibernate.engine.jdbc.spi.StatementPreparer;

import com.github.docteurdux.test.RunnableWithArgs;

public class DummyStatementPreparer implements StatementPreparer {

	private RunnableWithArgs<PreparedStatement> prepareStatementRWA;

	@Override
	public Statement createStatement() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PreparedStatement prepareStatement(String sql) {
		if (prepareStatementRWA != null) {
			return prepareStatementRWA.run(sql);
		}
		return null;
	}

	public void setPrepareStatementRWA(RunnableWithArgs<PreparedStatement> prepareStatementRWA) {
		this.prepareStatementRWA = prepareStatementRWA;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, boolean isCallable) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public PreparedStatement prepareQueryStatement(String sql, boolean isCallable, ScrollMode scrollMode) {
		// TODO Auto-generated method stub
		return null;
	}

}
