package dux.org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.DB2IdentityColumnSupport;
import org.junit.Before;
import org.junit.Test;

import com.github.docteurdux.test.AbstractTest;
import com.github.docteurdux.test.Done;

@Done
public class DB2IdentityColumnSupportTest extends AbstractTest {

	private String anyTable;
	private String anyColumn;
	private int anyType;

	@Before
	public void before() {
		anyTable = "anyTable";
		anyColumn = "anyColumn";
		anyType = 0;
	}

	@Test
	public void test() {

		DB2IdentityColumnSupport ics = new DB2IdentityColumnSupport();

		at(ics.supportsIdentityColumns());
		aeq("values identity_val_local()", ics.getIdentitySelectString(anyTable, anyColumn, anyType));
		aeq("generated by default as identity", ics.getIdentityColumnString(anyType));
		aeq("default", ics.getIdentityInsertString());
	}
}
