package dux.org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.H2IdentityColumnSupport;
import org.junit.Before;
import org.junit.Test;

import com.github.docteurdux.test.AbstractTest;
import com.github.docteurdux.test.Done;

@Done
public class H2IdentityColumnSupportTest extends AbstractTest {
	
	private int anyType;
	private String anyTable;
	private String anyColumn;

	@Before
	public void before() {
		anyType = 0;
		anyTable = "anyTable";
		anyColumn = "anyColumn";
	}

	@Test
	public void test() {

		H2IdentityColumnSupport ics = new H2IdentityColumnSupport();

		at(ics.supportsIdentityColumns());
		aeq("generated by default as identity", ics.getIdentityColumnString(anyType));
		aeq("call identity()", ics.getIdentitySelectString(anyTable, anyColumn, anyType));
		aeq("null", ics.getIdentityInsertString());
	}
}
