package dux.org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.HANAIdentityColumnSupport;
import org.junit.Test;

import com.github.docteurdux.test.AbstractTest;
import com.github.docteurdux.test.Done;

@Done
public class HANAIdentityColumnSupportTest extends AbstractTest {
	@Test
	public void test() {
		HANAIdentityColumnSupport ics = new HANAIdentityColumnSupport();
		aeq(true, ics.supportsIdentityColumns());
		aeq("select current_identity_value() from table", ics.getIdentitySelectString("table", "column", 0));
		aeq("generated by default as identity", ics.getIdentityColumnString(0));

	}
}
