package dux.org.hibernate.dialect.identity;

import org.hibernate.dialect.identity.IdentityColumnSupportImpl;
import org.hibernate.dialect.identity.Teradata14IdentityColumnSupport;
import org.junit.Before;
import org.junit.Test;

import com.github.docteurdux.test.AbstractTest;
import com.github.docteurdux.test.Done;

@Done
public class Teradata14IdentityColumnSupportTest extends AbstractTest {

	private int anyType;

	@Before
	public void before() {
		anyType = 0;
	}

	@Test
	public void test() {

		aeq(IdentityColumnSupportImpl.class, Teradata14IdentityColumnSupport.class.getSuperclass());

		Teradata14IdentityColumnSupport ics = new Teradata14IdentityColumnSupport();

		at(ics.supportsIdentityColumns());
		aeq("generated by default as identity not null", ics.getIdentityColumnString(anyType));
		aeq("null", ics.getIdentityInsertString());

	}

}
